/**
 * Relationship driver events — discrete, personality-triggered bonds/ruptures that move the
 * graph and surface as `RELATIONSHIP` feed lines.
 *
 * Spec: specs/behaviors/relationship-events.md
 * Deltas: specs/behaviors/relationship-graph.md#strength-shifts
 *
 * Two families:
 *  - **Peril response** (adventurer-only): the two branches — SHARED_DANGER and BETRAYAL — of a
 *    single combat moment (an ally at NEAR_DEATH). Detection reads the beats already generated by
 *    the combat resolver; application is the authoritative write site called from
 *    `questResolutionSubscriber`.
 *  - **Town-life drivers** (KINDNESS / RIVALRY_SPARK) live in a per-tick subscriber (below).
 *
 * Edges are symmetric (`graph[A][B] === graph[B][A]`), so a driver moves the bond by ONE delta;
 * the per-side "who feels it more" asymmetry the spec describes is carried by the per-actor
 * history tokens → beliefs (SAVED_BY → OWES on the saved side, BETRAYED_BY → DISTRUSTS on the
 * betrayed side), not by a directional edge strength.
 */
import type { ActorId, CombatBeat, PersonalityAxes, RelationshipDriverSubtype, SimulationContext } from '../world/types.js';
import { applyStrengthShift, detectThresholdEvents, strengthToType } from './graph.js';
import { emitEvent } from '../events/eventBus.js';
import { appendHistoryEvent } from '../adventurers/HistoryLayer.js';
import { isNpc } from '../world/actors.js';
import { actorView, pairKey as socialPairKey, type EncounterActor } from '../events/socialResolver.js';
import { questVolunteerWeight } from '../adventurers/personality.js';
import { upsertMoodFactor } from '../adventurers/mood.js';
import type { MoodFactor } from '../world/types.js';

// ---------------------------------------------------------------------------
// Driver deltas — canonical magnitudes in relationship-graph.md#strength-shifts.
// Edges are symmetric, so each driver moves the bond by ONE delta (the spec's
// per-side asymmetry is carried by history tokens → beliefs, not edge strength).
// ---------------------------------------------------------------------------

/** SHARED_DANGER mutual warm — additive to the routine co-quest +8 (peril moment only). */
export const SHARED_DANGER_DELTA = 12;
/** BETRAYAL bond rupture — the abandoned victim also gets a BETRAYED_BY token + crisis flag. */
export const BETRAYAL_DELTA = -18;
/** KINDNESS mutual warm (symmetric edge; the "recipient warms more" asymmetry is carried by a
 *  larger recipient mood factor, not a directional edge strength). */
export const KINDNESS_DELTA = 7;
/** RIVALRY_SPARK mutual cooling; the steeper value applies when the spark crosses into ENEMY. */
export const RIVALRY_DELTA = -10;
export const RIVALRY_ENEMY_DELTA = -14;

// ---------------------------------------------------------------------------
// Town-life driver triggers (KINDNESS / RIVALRY_SPARK) — personality-driven probabilities.
// All firing is gated by these and rolled through ctx.rng in the subscriber below; the
// probabilities are pure so tests assert the shift, not a rolled outcome.
// ---------------------------------------------------------------------------

const KINDNESS_BASE = 0.03;   // per-eligible-tick base, scaled by generosity ∈ [0,1]
const RIVALRY_BASE = 0.05;    // per-eligible-tick base for a fully-driven shared-goal clash

/** Generosity ∈ [0,1] — how readily an actor extends an unprompted kindness (relationship-events.md). */
export function generosity(p: PersonalityAxes): number {
  return (p.empathy * 0.5 + p.loyalty * 0.3 + (100 - p.greed) * 0.2) / 100;
}

/** Per-tick probability that `p` initiates a KINDNESS. Zero unless the empathy/loyalty gate is
 *  met; otherwise scales with generosity. */
export function kindnessInitiativeProb(p: PersonalityAxes): number {
  if (p.empathy < 55 && p.loyalty < 60) return 0; // initiator gate
  return KINDNESS_BASE * generosity(p);
}

/** Per-tick probability that two co-present actors ignite a RIVALRY_SPARK. Zero unless they share
 *  a goal AND both are ambitious (a lopsided contest never sparks); scales with combined ambition,
 *  low mutual empathy, and mood strain. */
export function rivalrySparkProb(
  a: PersonalityAxes,
  b: PersonalityAxes,
  sharedGoal: boolean,
  moodStrain = 0,
): number {
  if (!sharedGoal) return 0;
  if (a.ambition < 60 || b.ambition < 60) return 0; // both must be driven
  const ambitionFactor = (a.ambition + b.ambition) / 200;          // [0.6, 1]
  const empathyFactor = 1 - Math.min(a.empathy, b.empathy) / 100;  // low mutual empathy → higher
  return RIVALRY_BASE * ambitionFactor * (0.5 + 0.5 * empathyFactor) * (1 + moodStrain);
}

/** Canonical sorted pair key "A-B" (matches socialResolver.pairKey). */
function pairKey(a: ActorId, b: ActorId): string {
  return [a, b].sort().join('-');
}

export type PerilPair = [victim: ActorId, other: ActorId];

export type PerilPairs = {
  /** (near-death victim, defender) — a bond forged under lethal threat. */
  sharedDanger: PerilPair[];
  /** (near-death victim, hesitator) — an abandonment while the ally was dying. */
  betrayal: PerilPair[];
};

/**
 * Read the peril branches out of a resolved quest's combat beats.
 *
 * A peril moment exists only when some ally hit `NEAR_DEATH`. For each near-death **survivor**
 * (a victim still in `survivorIds`), every other survivor who performed `DEFEND_ALLY` reads as a
 * shared-danger partner; every other survivor who `HESITATE`d (and did NOT also defend) reads as a
 * betrayer. A member who both defended and hesitated is treated as a defender — the save dominates.
 *
 * The beat model carries actor + action but no target, so attribution is party-wide: this mirrors
 * the existing `SAVED_BY` derivation in `questSystem.ts`, which credits every defender to every
 * other member.
 */
export function detectPerilPairs(beats: CombatBeat[], survivorIds: ActorId[]): PerilPairs {
  const survivors = new Set(survivorIds);

  const victims = new Set<ActorId>();
  const defenders = new Set<ActorId>();
  const hesitators = new Set<ActorId>();
  for (const b of beats) {
    if (!survivors.has(b.actorId)) continue; // only survivors bond/betray
    if (b.action === 'NEAR_DEATH') victims.add(b.actorId);
    else if (b.action === 'DEFEND_ALLY') defenders.add(b.actorId);
    else if (b.action === 'HESITATE') hesitators.add(b.actorId);
  }

  const sharedDanger: PerilPair[] = [];
  const betrayal: PerilPair[] = [];
  if (victims.size === 0) return { sharedDanger, betrayal }; // no peril moment

  for (const victim of victims) {
    for (const defender of defenders) {
      if (defender === victim) continue;
      sharedDanger.push([victim, defender]);
    }
    for (const hesitator of hesitators) {
      if (hesitator === victim || defenders.has(hesitator)) continue; // a defender is never a betrayer
      betrayal.push([victim, hesitator]);
    }
  }

  return { sharedDanger, betrayal };
}

/**
 * Authoritative write site for the peril-response driver. Called from
 * `questResolutionSubscriber` with the resolved quest's beats and the surviving party. Applies
 * each detected branch: a symmetric strength shift (recorded in edge history), the driver's own
 * `RELATIONSHIP` feed line, and — for a BETRAYAL — the `BETRAYED_BY` memory on the victim plus a
 * crisis flag for the social system. A boundary crossing also emits its `LIFECYCLE` threshold
 * event (drivers are causes; thresholds are milestones). Adventurer-only: an NPC endpoint is
 * skipped (belt-and-braces; parties are adventurer-only anyway).
 */
export function applyPerilResponse(
  ctx: SimulationContext,
  survivorIds: ActorId[],
  beats: CombatBeat[],
): SimulationContext {
  const { sharedDanger, betrayal } = detectPerilPairs(beats, survivorIds);
  if (sharedDanger.length === 0 && betrayal.length === 0) return ctx;

  const tick = ctx.worldTime.tick;
  let next = ctx;

  const applyDriver = (
    victim: ActorId,
    other: ActorId,
    delta: number,
    kind: RelationshipDriverSubtype,
    isBetrayal: boolean,
  ): void => {
    if (isNpc(victim) || isNpc(other)) return; // adventurer-only
    const edge = next.relationships.get(victim)?.get(other);
    if (!edge) return; // no shared edge → nothing to move
    const prior = edge.strength;

    const graph = applyStrengthShift(next.relationships, victim, other, delta, tick, kind);
    const newStrength = graph.get(victim)!.get(other)!.strength;
    next = { ...next, relationships: graph };

    if (isBetrayal) {
      // Write the BETRAYED_BY memory that was previously never emitted (beliefs.ts → DISTRUSTS),
      // naming the betrayer, and flag the pair so the next social encounter can escalate.
      const adv = next.adventurers.get(victim);
      if (adv) {
        const history = appendHistoryEvent(adv.history, {
          tick, kind: 'BETRAYED_BY', involvedIds: [other], weight: 3,
        });
        next = { ...next, adventurers: new Map(next.adventurers).set(victim, { ...adv, history }) };
      }
      next = { ...next, pendingCrises: new Set(next.pendingCrises).add(pairKey(victim, other)) };
    }

    next = emitEvent(next, { kind: 'RELATIONSHIP', subtype: kind, participantIds: [victim, other] });

    for (const te of detectThresholdEvents(victim, other, prior, newStrength)) {
      next = emitEvent(next, { kind: 'LIFECYCLE', subtype: te.type, involvedIds: [te.adventurerId1, te.adventurerId2] });
    }
  };

  for (const [victim, defender] of sharedDanger) applyDriver(victim, defender, SHARED_DANGER_DELTA, 'SHARED_DANGER', false);
  for (const [victim, hesitator] of betrayal) applyDriver(victim, hesitator, BETRAYAL_DELTA, 'BETRAYAL', true);

  return next;
}

// ---------------------------------------------------------------------------
// Town-life driver subscriber (KINDNESS / RIVALRY_SPARK)
//
// A per-tick detector that runs DEAD-LAST in the loop (after every already-baselined intra-tick
// rng draw, incl. thought whispers) so a new rng consumer never shifts the stream the
// decision/quest/social systems see (rng-stream discipline, per core CLAUDE.md). Each eligible
// pair fires at most one driver per cooldown window (once/day + jitter), keyed off decisionCooldowns.
// ---------------------------------------------------------------------------

const KINDNESS_MIN_STRENGTH = 11; // ACQUAINTANCE-or-higher target (relationship-events.md)
const ENEMY_STRENGTH = -51;       // an ENEMY edge accumulates no voluntary driver
const DRIVER_COOLDOWN_BASE = 24;  // once-per-day floor (24 ticks)
const DRIVER_COOLDOWN_JITTER = 24; // + [0,24) jitter → window [24, 48)
const KINDNESS_MOOD_RECEIVED = 6; // recipient warms more (being valued)
const KINDNESS_MOOD_GIVEN = 3;    // giver's quieter lift

function isTownEligible(a: EncounterActor): boolean {
  const present = a.state !== 'ON_QUEST' && a.state !== 'IN_DUNGEON' && a.state !== 'DEAD' && a.state !== 'RETIRED';
  const awake = a.activityState?.current !== 'SLEEPING';
  return present && awake;
}

/** Two adventurers share a goal if they share a personal goal, or both volunteer strongly for the
 *  same available quest (goal alignment via questVolunteerWeight). NPCs carry no goal, so a pair
 *  with an NPC endpoint never shares a goal in v1 (NPC rivalry seeding lands with p13b). */
function shareGoal(ctx: SimulationContext, idA: ActorId, idB: ActorId): boolean {
  const a = ctx.adventurers.get(idA);
  const b = ctx.adventurers.get(idB);
  if (!a || !b) return false;
  if (a.identity.personalGoal === b.identity.personalGoal) return true;
  for (const q of ctx.questBoard.available) {
    if (questVolunteerWeight(a, q) > 0.5 && questVolunteerWeight(b, q) > 0.5) return true;
  }
  return false;
}

function applyMoodFactor(ctx: SimulationContext, id: ActorId, factor: MoodFactor): SimulationContext {
  const adv = ctx.adventurers.get(id);
  if (adv) {
    return { ...ctx, adventurers: new Map(ctx.adventurers).set(id, { ...adv, moodFactors: upsertMoodFactor(adv.moodFactors, factor) }) };
  }
  const npc = ctx.notableNpcs.get(id);
  if (npc) {
    return { ...ctx, notableNpcs: new Map(ctx.notableNpcs).set(id, { ...npc, moodFactors: upsertMoodFactor(npc.moodFactors, factor) }) };
  }
  return ctx;
}

/** Apply one town-life driver: symmetric shift (recorded in history) + its RELATIONSHIP line +
 *  any threshold LIFECYCLE event + the per-pair cooldown. Returns the new context. */
function applyTownDriver(
  ctx: SimulationContext,
  idA: ActorId,
  idB: ActorId,
  subtype: 'KINDNESS' | 'RIVALRY_SPARK',
  delta: number,
  tick: number,
  cooldownKey: string,
): SimulationContext {
  const prior = ctx.relationships.get(idA)!.get(idB)!.strength;
  let next: SimulationContext = {
    ...ctx,
    relationships: applyStrengthShift(ctx.relationships, idA, idB, delta, tick, subtype),
  };
  const newStrength = next.relationships.get(idA)!.get(idB)!.strength;

  next = emitEvent(next, { kind: 'RELATIONSHIP', subtype, participantIds: [idA, idB] });
  for (const te of detectThresholdEvents(idA, idB, prior, newStrength)) {
    next = emitEvent(next, { kind: 'LIFECYCLE', subtype: te.type, involvedIds: [te.adventurerId1, te.adventurerId2] });
  }
  // A rivalry that crosses into ENEMY carries a crisis flag into the social system.
  if (subtype === 'RIVALRY_SPARK' && strengthToType(newStrength) === 'ENEMY') {
    next = { ...next, pendingCrises: new Set(next.pendingCrises).add(socialPairKey(idA, idB)) };
  }
  const cooldown = tick + DRIVER_COOLDOWN_BASE + Math.floor(next.rng.next() * DRIVER_COOLDOWN_JITTER);
  next = { ...next, decisionCooldowns: new Map(next.decisionCooldowns).set(cooldownKey, cooldown) };
  return next;
}

export function townDriverSubscriber(ctx: SimulationContext): SimulationContext {
  const ids: ActorId[] = [];
  for (const [id, adv] of ctx.adventurers) if (isTownEligible(adv)) ids.push(id);
  for (const id of ctx.notableNpcs.keys()) ids.push(id);
  if (ids.length < 2) return ctx;

  const tick = ctx.worldTime.tick;
  let next = ctx;

  for (let i = 0; i < ids.length; i++) {
    for (let j = i + 1; j < ids.length; j++) {
      const idA = ids[i]!;
      const idB = ids[j]!;
      if (isNpc(idA) && isNpc(idB)) continue; // no NPC↔NPC relationships in scope

      const cooldownKey = `DRIVER:${socialPairKey(idA, idB)}`;
      if ((next.decisionCooldowns.get(cooldownKey) ?? 0) > tick) continue;

      const edge = next.relationships.get(idA)?.get(idB);
      if (!edge) continue; // only known pairs carry drivers
      const a = actorView(next, idA);
      const b = actorView(next, idB);
      if (!a || !b) continue;

      // RIVALRY_SPARK — needs a shared goal, clashing ambition, and a non-enemy edge.
      if (edge.strength > ENEMY_STRENGTH) {
        const rp = rivalrySparkProb(a.personality, b.personality, shareGoal(next, idA, idB));
        if (rp > 0 && next.rng.next() < rp) {
          const delta = (edge.strength + RIVALRY_DELTA) <= ENEMY_STRENGTH ? RIVALRY_ENEMY_DELTA : RIVALRY_DELTA;
          next = applyTownDriver(next, idA, idB, 'RIVALRY_SPARK', delta, tick, cooldownKey);
          continue;
        }
      }

      // KINDNESS — the more generous of the pair extends it on an ACQUAINTANCE-or-higher edge.
      if (edge.strength >= KINDNESS_MIN_STRENGTH) {
        const initiatorIsA = generosity(a.personality) >= generosity(b.personality);
        const initiator = initiatorIsA ? a : b;
        const recipientId = initiatorIsA ? idB : idA;
        const kp = kindnessInitiativeProb(initiator.personality);
        if (kp > 0 && next.rng.next() < kp) {
          next = applyTownDriver(next, initiator.id, recipientId, 'KINDNESS', KINDNESS_DELTA, tick, cooldownKey);
          next = applyMoodFactor(next, recipientId, { id: 'KINDNESS_RECEIVED', label: 'Shown kindness', value: KINDNESS_MOOD_RECEIVED, decayRate: 0.15 });
          next = applyMoodFactor(next, initiator.id, { id: 'KINDNESS_GIVEN', label: 'Did a kindness', value: KINDNESS_MOOD_GIVEN, decayRate: 0.15 });
          continue;
        }
      }
    }
  }

  return next;
}
